name: Update Fund Values

on:
  schedule:
    - cron: '0 */2 * * *'  # 每2小时运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install --upgrade git+https://github.com/xiaopc/qdii-value.git#egg=qdii_value
        pip install pygments  # 用于ANSI颜色转HTML
        
    - name: Update fund values
      run: |
        cd scripts
        python update_data.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add public/
        git commit -m "自动更新基金估值数据"
        git push
