name: Update Fund Values

on:
  schedule:
   - cron: '30 1-15 * * *'  # 每 1 小时运行一次 (UTC time)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install --upgrade git+https://github.com/xiaopc/qdii-value.git#egg=qdii_value
     
    - name: Update fund values
      working-directory: scripts
      run: |
        python render_html.py
        
    - name: Commit and push changes
      run: |
        cp scripts/index.html  data/index.html 
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add data/index.html
        git commit -m "自动更新基金估值数据"
        git push
