name: Update Fund Values

on:
  schedule:
   - cron: '30 */2 * * *'  # 每2小时运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install --upgrade git+https://github.com/xiaopc/qdii-value.git#egg=qdii_value
        sudo apt-get install expect
        pip install pygments pygments-ansi-color
     
    - name: Update fund values
      working-directory: scripts
      run: |
        expect -c '
        log_user 1
        spawn qdii-value 968061
        sleep 5
        send \003
        sleep 0.01
        send \003
        expect eof
        ' | tee output.txt
        python convert_to_html.py
        
    - name: Commit and push changes
      run: |
        cp scripts/output.html  data/output.html 
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add data/output.html
        git commit -m "自动更新基金估值数据"
        git push
