name: Update Fund Values

on:
  schedule:
    - cron: '0 */2 * * *'  # 每2小时运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install --upgrade git+https://github.com/xiaopc/qdii-value.git#egg=qdii_value
        pip install pygments  # 用于ANSI颜色转HTML
        pip install pygments-ansi-color
    
    - name: Install ImageMagick
      run: sudo apt-get install imagemagick -y
     
    - name: Update fund values
      run: |
        cd scripts
        timeout 60 qdii-value 968061 > output.txt
        convert -background black -fill white -font Courier -pointsize 14 label:@"output.txt" output.png
        
    - name: Commit and push changes
      run: |
        mkdir data
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add data/output.png
        git commit -m "自动更新基金估值数据"
        git push
