name: Update Fund Values

on:
  #schedule:
  # - cron: '0 */2 * * *'  # 每2小时运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install --upgrade git+https://github.com/xiaopc/qdii-value.git#egg=qdii_value
        sudo apt-get install expect
    
    - name: Install ImageMagick
      run: |
        sudo add-apt-repository -y ppa:ubuntuhandbook1/imagick
        sudo apt-get update
        sudo apt-get install -y imagemagick
     
    - name: Update fund values
      working-directory: scripts
      run: |
        expect -c '
        log_user 1
        spawn qdii-value 968061
        sleep 10
        send \003
        ' | tee output.txt
        cat output.txt | magick -background black -fill white -font Courier -pointsize 14 caption:@- output.png
        
    - name: Commit and push changes
      run: |
        mkdir data
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add data/output.png
        git commit -m "自动更新基金估值数据"
        git push
