name: Update Fund Values

on:
  schedule:
    # 01:00, 01:30, ..., 03:30 UTC（对应 09:00–11:30 北京时间）
    - cron: '0,30 1-3 * * *'
    # 05:00, 05:30, ..., 07:30 UTC（对应 13:00–15:30 北京时间）
    - cron: '0,30 5-7 * * *'
    # 每 2 小时（UTC 16–23 和 0–0 UTC = 北京时间 00–08, 16–23）
    - cron: '0 8,12,20 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: pip-local-${{ runner.os }}-v1
        restore-keys: |
          pip-local-${{ runner.os }}-
        
    - name: Install dependencies
      run: |
        pip install --upgrade git+https://github.com/xiaopc/qdii-value.git#egg=qdii_value
          
    - name: Update fund values
      working-directory: scripts
      run: |
        python render_html.py
        
    - name: Commit and push changes
      run: |
        cp scripts/index.html  data/index.html 
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add data/index.html
        git commit -m "自动更新基金估值数据"
        git push
